version: "2"

run:
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

formatters:
  enable:
    - gci
    - gofmt
    - goimports

severity:
  default: error
  # Overrides
  # rules:
  #   - linters:
  #       - errheck
  #     severity: error

issues:
  {}
  # e.g. skip generated code
  # fix: true
